### PR TITLE
Put the end time back onto a short calendar event.

### PR DESCRIPTION
**Pull request by FatBoyXPC**

### CODE REVIEW

**Comment by Baiqiang** [comment]
I wonder why there're so many commits.

**Comment by FatBoyXPC** [comment]
Because every time I pull from cubing ccm and I have local changes, it
makes me commit the pull. It's really annoying.

**Comment by Baiqiang** [comment]
I really didn't like so many unrelated commits. I would pull from cubing/ccm first and then commit my changes.

**Comment by Baiqiang** [comment]
How do you pull from cubing/ccm? I tried git pull git@github.com:cubing/ccm.git master and didn't meet your situation.

**Comment by FatBoyXPC** [comment]
Make a change to your code. Commit it, but don't push. If you pull from
cubing/ccm master, and there are updates, it will make you commit your
merge.

**Comment by FatBoyXPC** [comment]
How do you suggest I fix this? To my knowledge, the only way I can prevent this from happening is by doing a rebase, and I'm not too sure how it works. I was reading up on it and they had some guidelines of when to and not to do a rebase, so I figured for now it's better left alone.

**Comment by Baiqiang** [comment]
How about reset your fork to the head of cubing/ccm and then commit your change? Your commit only affects one file. That's easy to do.

**Comment by Baiqiang** [comment]
If I had so many unrelated commits, I'd rather delete my fork and then fork a new one and commit my change to the new fork.

**Pull request closed without merging**
