### PR TITLE
Broke out each Mongo collection to its own file, changing as little as possible

### PR DESCRIPTION
**Pull request by larspetrus**

### CODE REVIEW

**Comment by FatBoyXPC** [comment]
Wow! This is definitely one of these things that I thought needed to happen, but felt that things work just fine as they are, so I wasn't worried about doing it right now.

Would you be opposed to putting these in a collections directory of some sort? Or pre/post-fixing them with "collection"? I'm not a fan of the "you will need to open this file to know what it is" sort of approach here.

**Comment by larspetrus** [comment]
A collections directory absolutely how I want it to be, but it has complications that I didn't want to deal with right now. Maybe I should.

The leading underscores in the file names are there to force loading order. The collections depend on the wca data, so it gets a double underscore. Other code depends on the collections, so they get one underscore. The individual collections depend on _collections.js, but by luck that is alphabetically before all of them, so that works anyway.

If you create a directory, it will be loaded before the top level files (according to Jeremy), so then we'd have to either force the wca code to come first somehow, or (my favorite) make the schema code not execute at load time.

That seems complicated, so I wanted a quick improvement rather than a big project to reach perfection, but I'm open to reconsider that.

**Comment by FatBoyXPC** [comment]
While this isn't the optimal solution, we could create a __wca directory and put that file in there. The nice thing about this, is if we ever wanted to expand __wca.js into multiple files, we could that way.

**Comment by larspetrus** [comment]
A separate _WCA directory feels too hacky for me.

Dropping __wca.js into the collections directory does work, and I feel better about that hack.

Can't these things be managed explicitly? I tried require, but it didn't work.

**Comment by FatBoyXPC** [comment]
Yeah, it feels really hacky to me, too. Is anything other than collections dependent on __wca.js? If so, I don't like putting it in the collections directory.

**Comment by jfly** [comment]
Thanks for taking this on, Lars! This is definitely better than what we had.

Lets bite the bullet and put these in a `both/collections/` folder (and remove the ugly underscores from the names). Lets also move `__wca.js` to the `both/components/` directory, and rename `both/components/` to `both/_/`.

Unfortunately, meteor eschews node's require() mechanism in favor of this unweildy concatenation system. I imagine they did this because client side require() is tricky and confusing to implement, due to javascript's lack of blocking IO.

If we want fine grained control over file load order, we can use meteor packages. See "Method 3" under "Organizing Your Project" on http://docs.meteor.com/#/full/structuringyourapp. I'd rather not do this for now.

**Comment by larspetrus** [comment]
This makes sense. Except that "_" is on the undescriptive side. Why not use the meteor standard "lib"?

**Comment by jfly** [comment]
Ohh, sounds good! I didn't realize that `lib` works recursively =)

**Comment by jfly** [comment]
LGTM :ship: it!

**Pull request merged**
